### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by giulio333** [SigireddyBalasai/AsyncPywhatKit#10]
AttributeError: module 'AsyncPywhatKit' has no attribute 'sendwhatmsg'

**Comment by SigireddyBalasai** [comment]
A very Sincere sorry for not upgrading the docs my friend the working code is 
from AsyncPywhatKit.src import sendwhatmsg

**Comment by 95caparra** [comment]
Help me

AsyncPywhatKit.src import sendwhatmsg

"AsyncPywhatKit" is not definedPylance[reportUndefinedVariable](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUndefinedVariable)
(function) AsyncPywhatKit: Any

    AsyncPywhatKit.src import sendwhatmsg
                       ^^^^^^
SyntaxError: invalid syntax

**Comment by SigireddyBalasai** [comment]
My dear friend it is from AsyncPywhatKit import sendwhatmsg not you typed it is not an issue with library but python itself change it and let me know the result

**Comment by SigireddyBalasai** [comment]
from AsyncPywhatKit.src import sendwhatmsg

**Comment by SigireddyBalasai** [comment]
from AsyncPywhatKit.src import sendwhatmsg

**Comment by 95caparra** [comment]
me retorna el siguiente error

![image](https://user-images.githubusercontent.com/40253044/235367982-8f6dd3ae-1f00-443b-a849-80931c510081.png)


![image](https://user-images.githubusercontent.com/40253044/235368008-cb3e873f-c02b-4e6d-b7c9-35d3d24185d2.png)

**Comment by SigireddyBalasai** [comment]
it is due to two async environments i had sorted it out by making asyncPywhatkit compromised in the new release upgrade it to new version by using 
pip install --upgrade AsyncPywhatKit 
and then try running again

**Comment by SigireddyBalasai** [comment]
can i close this . i will do this if no problem and feel free to share result
