### ISSUE TITLE
 I have this error

### ISSUE THREAD

**Issue by crgv7** [SigireddyBalasai/AsyncPywhatKit#12]
AttributeError: module 'AsyncPywhatKit' has no attribute 'src'

**Comment by SigireddyBalasai** [comment]
Can you post a screenshot

**Comment by crgv7** [comment]
![screen](https://user-images.githubusercontent.com/123612279/232670860-3f994b5a-97ba-4a19-858c-885d33e43bc7.png)

**Comment by SigireddyBalasai** [comment]
Ok use from AsyncPywhatKit.src import sendwhatmsg_to_group_instantly

**Comment by SigireddyBalasai** [comment]
Comment the result

**Comment by SigireddyBalasai** [comment]
sorry for this i gave my pc to repair which took time
please upgrade by using pip install --upgrade AsyncPywhatKit which solves the issue

**Comment by SigireddyBalasai** [comment]
please feel free to share result

**Comment by SigireddyBalasai** [comment]
i will close this tomorrow if you don't have any problem
