### ISSUE TITLE
Send Multiple Images at once

### ISSUE THREAD

**Issue by jak83A** [SigireddyBalasai/AsyncPywhatKit#4]
**Related Problem**
It would be simply more convenient to send multiple images once instead of on-by-one.

**Feature Description**
I think it would be best to work

a) with a list containing the target img paths as its elements

and/or

b) with a target folder containing the images

**Comment by SigireddyBalasai** [comment]
Target image list is created it will be released to pypi today

**Comment by SigireddyBalasai** [comment]
new release solved that

**Comment by SigireddyBalasai** [comment]
thank you
